//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BztErrorsManager.Model.ModelBzt
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_ReceiveLocation
    {
        public int Id { get; set; }
        public int AdapterId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ReceiveHandlerId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public System.DateTime DateModified { get; set; }
        public string Comment { get; set; }
        public int OperatingWindowEnabled { get; set; }
        public Nullable<System.DateTime> ActiveStartDT { get; set; }
        public Nullable<System.DateTime> ActiveStopDT { get; set; }
        public bool StartDTEnabled { get; set; }
        public Nullable<System.DateTime> SrvWinStartDT { get; set; }
        public bool StopDTEnabled { get; set; }
        public Nullable<System.DateTime> SrvWinStopDT { get; set; }
        public int Disabled { get; set; }
        public string CustomCfg { get; set; }
        public Nullable<System.Guid> uidCustomCfgID { get; set; }
        public bool bSSOMappingExists { get; set; }
        public string InboundTransportURL { get; set; }
        public string InboundAddressableURL { get; set; }
        public Nullable<int> ReceivePipelineId { get; set; }
        public string ReceivePipelineData { get; set; }
        public int ReceivePortId { get; set; }
        public int IsPrimary { get; set; }
        public int Fragmentation { get; set; }
        public string nvcCustomData { get; set; }
        public Nullable<int> SendPipelineId { get; set; }
        public string EncryptionCert { get; set; }
        public string EncryptionCertThumbPrint { get; set; }
        public string Description { get; set; }
        public string SendPipelineData { get; set; }
    
        public virtual adm_Adapter adm_Adapter { get; set; }
    }
}
