//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BztErrorsManager.Model.ModelBzt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BizTalkMgmtDbEntities : DbContext
    {
        public BizTalkMgmtDbEntities()
            : base("name=BizTalkMgmtDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adm_ReceiveLocation> adm_ReceiveLocation { get; set; }
        public virtual DbSet<adm_Adapter> adm_Adapter { get; set; }
    }
}
